# Generated by Django 6.0.4 on 2026-04-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
