# Generated by Django 6.0.4 on 2026-04-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_is_upcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='upcoming/')),
                ('description', models.TextField()),
                ('release_date', models.CharField(blank=True, help_text='e.g. Summer 2024', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
