# Generated by Django 6.0.4 on 2026-04-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_upcomingproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingproduct',
            options={'verbose_name': 'Upcoming Product', 'verbose_name_plural': 'Upcoming Products'},
        ),
    ]
