# Generated by Django 6.0.4 on 2026-04-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_upcomingproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upcoming/'),
        ),
        migrations.AlterField(
            model_name='upcomingproduct',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingproduct',
            name='release_date',
            field=models.CharField(blank=True, help_text='e.g. Summer 2024', max_length=50, null=True),
        ),
    ]
