# Generated by Django 5.2.4 on 2026-05-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_category_alter_product_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpcomingProduct',
        ),
    ]
